version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - backend
    # Uncomment the next line to use a non-root user for all processes.
    # user: node

  db:
    image: postgres:16.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql@16/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: medusajs

    networks:
      - backend

    ports:
      - '5432:5432'
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

    networks:
      - backend

volumes:
  postgres-data:


networks:
  backend:
